// Generated by CoffeeScript 1.6.2
(function() {
  var currentGame, gameTimer;

  currentGame = void 0;

  gameTimer = void 0;

  timeStart(function() {
    var count;

    count = 0;
    return gameTimer = setInterval(function() {
      var timerDiv;

      count += 1;
      timerDiv = $('#timer')[0];
      return timerDiv.innerHTML = "Timer: " + count.toString() + " secs";
    }, 1000);
  });

  checkForWin(function() {
    if ($('.hidden').length === 0) {
      return clearInterval(gameTimer);
    }
  });

}).call(this);
