// Generated by CoffeeScript 1.6.2
(function() {
  var checkForWin, smallGame, timeStart;

  timeStart = function() {
    var count, gameTimer;

    count = 0;
    return gameTimer = setInterval(function() {
      var timerDiv;

      count += 1;
      timerDiv = $("#timer")[0];
      return timerDiv.innerHTML = "Timer: " + count.toString() + " secs";
    }, 1000);
  };

  checkForWin = function() {
    if ($('.hidden').length === 0) {
      return clearInterval(gameTimer);
    }
  };

  smallGame = function() {
    var letterArray, shuffledArray, square, _i, _len, _results;

    timeStart();
    letterArray = ["A", "A", "B", "B", "C", "C", "D", "D", "E", "E"];
    shuffledArray = _.shuffle(letterArray);
    _results = [];
    for (_i = 0, _len = shuffledArray.length; _i < _len; _i++) {
      square = shuffledArray[_i];
      _results.push((function() {
        var divElement;

        divElement = $("<div/>");
        divElement.attr('class', 'hidden');
        divElement.attr('data-id', square);
        divElement.append(square);
        divElement.on("click", function() {
          var revealedElements;

          console.log(this);
          revealedElements = $(".revealed");
          if (revealedElements.length === 0) {
            return $(this).addClass("revealed");
          } else if ($(".revealed").html() === $(this).html()) {
            $(this).addClass("matched");
            $(".revealed").addClass("matched");
            $(".revealed").unbind("click mouseover");
            $(".revealed").removeClass("hidden revealed");
            $(this).removeClass("hidden revealed");
            return checkForWin();
          } else {
            $(this).addClass("revealed");
            return setTimeout((function() {
              return $(".revealed").removeClass("revealed");
            }), 800);
          }
        });
        return $("#game_squares").append(divElement);
      })());
    }
    return _results;
  };

  $(".hidden").mouseover(function() {
    return $(this).addClass("hover");
  });

  $(".hidden").mouseout(function() {
    return $(this).removeClass("hover");
  });

  $(document).ready(function() {
    var letterArray;

    letterArray = [];
    return $("#easy_btn").on("click", smallGame);
  });

}).call(this);
